version: "3.4"

services:
  db:
    container_name: 'api-cadastro-db'
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api-cadastro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db2:/var/lib/postgresql/data
volumes:
  db2: