version: "3.4"

services:
  db:
    container_name: 'api-cadastro-db'
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: APICADASTRO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db1:/var/lib/postgresql/data
  api-cadastro:
    container_name: 'api-cadastro'
    build:
      context: .
    ports:
      - "5000:5000"
volumes:
  db1: