CREATE TABLE USER_AUTH (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(256),
    WORDPASS VARCHAR(72)
);

CREATE TABLE USER_PROFILE(
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER UNIQUE NOT NULL,
    USER_NAME VARCHAR(60),
    BIRTH_DAY DATE,
    FOREIGN KEY (USER_ID) REFERENCES USER_AUTH(ID)
);

CREATE TABLE USER_ADDRESS(
    ID SERIAL PRIMARY KEY,
    USER_PROFILE_ID INTEGER UNIQUE NOT NULL,
    CITY_STATE VARCHAR(50),
    CITY VARCHAR(50),
    NEIGHBOR VARCHAR(50),
    STREET VARCHAR(50),
    HOUSE_NUMBER VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    FOREIGN KEY (USER_PROFILE_ID) REFERENCES USER_PROFILE(ID)
);