CREATE TABLE USER_AUTH (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(256) UNIQUE NOT NULL,
    PASS_WORD VARCHAR(72) NOT NULL,
    DELETED_AT DATE
);

CREATE TABLE USER_PROFILE(
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER UNIQUE NOT NULL,
    NAME VARCHAR(60),
    BIRTH_DAY DATE,
    GENDER VARCHAR(20),
    FOREIGN KEY (USER_ID) REFERENCES USER_AUTH(ID)
);

CREATE TABLE USER_ADDRESS(
    ID SERIAL PRIMARY KEY,
    USER_PROFILE_ID INTEGER NOT NULL,
    CITY_STATE VARCHAR(50),
    CITY VARCHAR(50),
    NEIGHBOR VARCHAR(50),
    STREET VARCHAR(50),
    HOUSE_NUMBER VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    FOREIGN KEY (USER_PROFILE_ID) REFERENCES USER_PROFILE(ID)
);